title: Autotechnik Troger
description: Auto-Ersatzteile in Unterlamm-Bad Loipersdorf
lang: de-AT
url: https://www.autotechnik-troger.at
baseurl: ""
theme: jekyll-theme-architect
show_downloads: false

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md

defaults:
  - scope:
      path: ""
    values:
      layout: default