title: Autotechnik Troger
description: Auto-Ersatzteile in Unterlamm-Bad Loipersdorf
lang: de-AT
url: https://www.autotechnik-troger.at
baseurl: ""
remote_theme: pages-themes/architect@v0.2.0
show_downloads: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md

defaults:
  - scope:
      path: ""
    values:
      layout: default